/**
 * Банк слов для Библейского Alias.
 *
 * Правила, по которым он собран:
 *
 *  - **Одно слово или короткое словосочетание.** Alias — игра про
 *    объяснение понятия, а не фразы. «Блудный сын» проходит, «И сказал Бог
 *    да будет свет» — нет.
 *  - **Уровень описывает слово, а не игрока.** «Легко» — школьный уровень
 *    и общая культура, «Средне» — знакомо тому, кто был на разборах,
 *    «Сложно» — начинается спорт.
 *  - **`gloss` — ровно одна строка.** Она читается вслух между раундами,
 *    пока компания ждёт следующего хода. Абзац здесь никто не дочитает.
 *  - **Ссылка разобрана на части, а не строкой.** `ref: [книга, глава,
 *    стих]` проверяется при заливке по настоящему тексту Синодального
 *    перевода: если стиха нет, сид падает. Строку так не проверить, и
 *    опечатка в сокращении книги ушла бы в продакшн незамеченной.
 *  - **Ссылка только там, где она однозначна.** У сквозных понятий
 *    («завет», «пророк», «покаяние») одного честного места нет, и выдумать
 *    его хуже, чем оставить пусто. Пустая ссылка — это не пробел в работе,
 *    а отказ соврать.
 *
 * Отдельно про категорию `IDIOM` — «Крылатые слова». Это вход в игру для
 * тех, кто Библию не читал: «козёл отпущения», «умыть руки», «манна
 * небесная» — слова, которыми человек пользуется каждый день, не зная,
 * откуда они. Такая компания начинает с категории, где заведомо всё знает,
 * и по ходу узнаёт, что всё это время цитировала Писание. Это лучший
 * первый раунд, который здесь можно предложить.
 *
 * Запуск: `pnpm --filter @bible-arena/api exec ts-node prisma/seed-alias.ts`
 */
import { PrismaClient } from '@prisma/client';
import type {
  AliasCategory,
  AliasDifficulty,
  AliasTestament,
} from '@bible-arena/shared';

const prisma = new PrismaClient();

/** Канонические номера книг (те же, что у `BibleVerse.bookId`). Латиницей,
 * чтобы ссылка в исходнике читалась как ссылка, а не как ещё одно русское
 * слово посреди русского текста. */
const B = {
  gen: 1,
  exo: 2,
  lev: 3,
  num: 4,
  deu: 5,
  jos: 6,
  jdg: 7,
  rut: 8,
  sa1: 9,
  sa2: 10,
  kg1: 11,
  kg2: 12,
  ezr: 15,
  neh: 16,
  est: 17,
  job: 18,
  psa: 19,
  pro: 20,
  isa: 23,
  jer: 24,
  eze: 26,
  dan: 27,
  hos: 28,
  amo: 30,
  jon: 32,
  mic: 33,
  mal: 39,
  mat: 40,
  mrk: 41,
  luk: 42,
  jhn: 43,
  act: 44,
  rom: 45,
  co1: 46,
  gal: 48,
  col: 51,
  th2: 53,
  ti1: 54,
  phm: 57,
  heb: 58,
  rev: 66,
} as const;

interface Entry {
  word: string;
  difficulty: AliasDifficulty;
  category: AliasCategory;
  testament: AliasTestament;
  gloss: string;
  /** `[bookId, chapter, verse]`. */
  ref?: readonly [number, number, number];
}

const E = 'EASY' as const;
const M = 'MEDIUM' as const;
const H = 'HARD' as const;

const WORDS: Entry[] = [
  // ——— ЛИЧНОСТИ · Ветхий Завет ———
  {
    word: 'Адам',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Первый человек, которого Бог поселил в саду Едемском.',
    ref: [B.gen, 2, 7],
  },
  {
    word: 'Ева',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Первая женщина, названная матерью всех живущих.',
    ref: [B.gen, 3, 20],
  },
  {
    word: 'Каин',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Старший сын Адама, убивший брата Авеля.',
    ref: [B.gen, 4, 8],
  },
  {
    word: 'Авель',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пастух, чью жертву принял Бог; убит собственным братом.',
    ref: [B.gen, 4, 4],
  },
  {
    word: 'Ной',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Построил ковчег и пережил потоп со своей семьёй.',
    ref: [B.gen, 6, 14],
  },
  {
    word: 'Авраам',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Вышел из своей земли по слову Бога и стал отцом множества народов.',
    ref: [B.gen, 12, 1],
  },
  {
    word: 'Сарра',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Жена Авраама, родившая сына в глубокой старости.',
    ref: [B.gen, 21, 2],
  },
  {
    word: 'Исаак',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Обещанный сын Авраама, которого отец готов был принести в жертву.',
    ref: [B.gen, 22, 9],
  },
  {
    word: 'Иаков',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Получил имя Израиль после ночной борьбы у потока.',
    ref: [B.gen, 32, 28],
  },
  {
    word: 'Исав',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Брат Иакова, отдавший первородство за чечевичную похлёбку.',
    ref: [B.gen, 25, 33],
  },
  {
    word: 'Иосиф',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Проданный братьями в Египет и ставший там вторым после фараона.',
    ref: [B.gen, 41, 41],
  },
  {
    word: 'Моисей',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Вывел народ из Египта и принял закон на Синае.',
    ref: [B.exo, 3, 10],
  },
  {
    word: 'Аарон',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Брат Моисея и первый первосвященник.',
    ref: [B.exo, 28, 1],
  },
  {
    word: 'Мариам',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Сестра Моисея, запевшая с тимпаном после перехода через море.',
    ref: [B.exo, 15, 20],
  },
  {
    word: 'Иисус Навин',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Преемник Моисея, введший народ в обещанную землю.',
    ref: [B.jos, 1, 2],
  },
  {
    word: 'Самсон',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Силач, чья сила была в некошеных волосах.',
    ref: [B.jdg, 16, 17],
  },
  {
    word: 'Далида',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Женщина, выведавшая у Самсона тайну его силы.',
    ref: [B.jdg, 16, 18],
  },
  {
    word: 'Гедеон',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Судья, победивший с тремястами воинов и трубами.',
    ref: [B.jdg, 7, 7],
  },
  {
    word: 'Девора',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророчица, судившая народ, сидя под пальмой.',
    ref: [B.jdg, 4, 5],
  },
  {
    word: 'Иеффай',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Судья, давший перед битвой обет, о котором потом пожалел.',
    ref: [B.jdg, 11, 30],
  },
  {
    word: 'Руфь',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Моавитянка, оставшаяся со свекровью и вошедшая в род Давида.',
    ref: [B.rut, 1, 16],
  },
  {
    word: 'Вооз',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Хозяин поля, взявший Руфь в жёны.',
    ref: [B.rut, 4, 13],
  },
  {
    word: 'Самуил',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, услышавший Божий зов ребёнком и помазавший первых царей.',
    ref: [B.sa1, 3, 10],
  },
  {
    word: 'Саул',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Первый царь Израиля, отвергнутый за непослушание.',
    ref: [B.sa1, 15, 23],
  },
  {
    word: 'Давид',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пастух, убивший Голиафа и ставший царём.',
    ref: [B.sa1, 17, 49],
  },
  {
    word: 'Голиаф',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Филистимский великан, побеждённый камнем из пращи.',
    ref: [B.sa1, 17, 4],
  },
  {
    word: 'Ионафан',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Сын Саула и вернейший друг Давида.',
    ref: [B.sa1, 18, 1],
  },
  {
    word: 'Соломон',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Царь, попросивший мудрости вместо богатства, и строитель храма.',
    ref: [B.kg1, 3, 9],
  },
  {
    word: 'Илия',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, взятый на небо в огненной колеснице.',
    ref: [B.kg2, 2, 11],
  },
  {
    word: 'Елисей',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Ученик Илии, просивший вдвое больше его духа.',
    ref: [B.kg2, 2, 9],
  },
  {
    word: 'Иона',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, бежавший от поручения и проведший три дня в чреве кита.',
    ref: [B.jon, 1, 17],
  },
  {
    word: 'Даниил',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Проведший ночь во рву со львами и оставшийся невредимым.',
    ref: [B.dan, 6, 16],
  },
  {
    word: 'Иов',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Потерял всё и не отрёкся от Бога.',
    ref: [B.job, 1, 21],
  },
  {
    word: 'Есфирь',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Царица, рискнувшая жизнью ради спасения своего народа.',
    ref: [B.est, 4, 16],
  },
  {
    word: 'Неемия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Восстановил стены Иерусалима, работая с оружием в руках.',
    ref: [B.neh, 4, 17],
  },
  {
    word: 'Ездра',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Книжник, читавший народу закон с деревянного возвышения.',
    ref: [B.neh, 8, 3],
  },
  {
    word: 'Исаия',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, ответивший на призыв словами «вот я, пошли меня».',
    ref: [B.isa, 6, 8],
  },
  {
    word: 'Иеремия',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, которого призвали ещё юношей и много раз не слушали.',
    ref: [B.jer, 1, 5],
  },
  {
    word: 'Иезекииль',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, увидевший поле сухих костей, которые ожили.',
    ref: [B.eze, 37, 4],
  },
  {
    word: 'Осия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, чей собственный брак стал притчей о неверности народа.',
    ref: [B.hos, 1, 2],
  },
  {
    word: 'Амос',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пастух из Фекои, обличавший неправый суд и роскошь.',
    ref: [B.amo, 1, 1],
  },
  {
    word: 'Мелхиседек',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Царь Салима и священник, встретивший Авраама хлебом и вином.',
    ref: [B.gen, 14, 18],
  },
  {
    word: 'Валаам',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, которого остановила заговорившая ослица.',
    ref: [B.num, 22, 28],
  },
  {
    word: 'Раав',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Жительница Иерихона, укрывшая соглядатаев и спасшая свой дом.',
    ref: [B.jos, 2, 4],
  },
  {
    word: 'Вирсавия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Женщина, из-за которой Давид совершил свой тяжелейший грех.',
    ref: [B.sa2, 11, 4],
  },
  {
    word: 'Нафан',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Пророк, обличивший Давида притчей об овечке бедняка.',
    ref: [B.sa2, 12, 7],
  },
  {
    word: 'Авессалом',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Сын Давида, поднявший мятеж и повисший волосами на дубе.',
    ref: [B.sa2, 18, 9],
  },
  {
    word: 'Иезавель',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Царица, преследовавшая пророков Господних.',
    ref: [B.kg1, 18, 4],
  },
  {
    word: 'Езекия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Царь, которому Бог прибавил пятнадцать лет жизни.',
    ref: [B.kg2, 20, 6],
  },
  {
    word: 'Иосия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Юный царь, при котором в храме нашли забытую книгу закона.',
    ref: [B.kg2, 22, 8],
  },
  {
    word: 'Навуходоносор',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss:
      'Вавилонский царь, разрушивший Иерусалим и видевший сон об истукане.',
    ref: [B.dan, 2, 1],
  },
  {
    word: 'Фараон',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Египетский правитель, не отпускавший народ, пока не пришли казни.',
    ref: [B.exo, 5, 2],
  },
  {
    word: 'Лот',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Племянник Авраама, выведенный ангелами из обречённого города.',
    ref: [B.gen, 19, 16],
  },
  {
    word: 'Жена Лота',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Обернулась назад и стала соляным столпом.',
    ref: [B.gen, 19, 26],
  },
  {
    word: 'Ревекка',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Напоила у колодца чужих верблюдов и стала женой Исаака.',
    ref: [B.gen, 24, 19],
  },
  {
    word: 'Рахиль',
    difficulty: M,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'За неё Иаков служил семь лет, и они показались ему днями.',
    ref: [B.gen, 29, 20],
  },
  {
    word: 'Лия',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Старшая сестра, которую подменили на брачном пиру.',
    ref: [B.gen, 29, 23],
  },
  {
    word: 'Лаван',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Тесть Иакова, десять раз менявший ему награду.',
    ref: [B.gen, 31, 41],
  },
  {
    word: 'Вениамин',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Младший сын Иакова, в чьём мешке нашли серебряную чашу.',
    ref: [B.gen, 44, 12],
  },
  {
    word: 'Ламех',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Потомок Каина, хвалившийся местью всемеро большей.',
    ref: [B.gen, 4, 24],
  },
  {
    word: 'Енох',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Ходил перед Богом и не увидел смерти — Бог взял его.',
    ref: [B.gen, 5, 24],
  },
  {
    word: 'Мафусал',
    difficulty: H,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Человек, проживший дольше всех в Писании.',
    ref: [B.gen, 5, 27],
  },

  // ——— ЛИЧНОСТИ · Новый Завет ———
  {
    word: 'Иоанн Креститель',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Крестил в Иордане и жил в пустыне на акридах и диком мёде.',
    ref: [B.mat, 3, 4],
  },
  {
    word: 'Мария',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Мать Иисуса, ответившая ангелу согласием.',
    ref: [B.luk, 1, 38],
  },
  {
    word: 'Иосиф Обручник',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Плотник из Назарета, которому ангел явился во сне.',
    ref: [B.mat, 1, 20],
  },
  {
    word: 'Гавриил',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Ангел, посланный к Марии с вестью о Сыне.',
    ref: [B.luk, 1, 26],
  },
  {
    word: 'Пётр',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Рыбак, ходивший по воде и трижды отрёкшийся до пения петуха.',
    ref: [B.mat, 26, 75],
  },
  {
    word: 'Андрей',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Первый призванный ученик, сразу приведший к Иисусу брата.',
    ref: [B.jhn, 1, 41],
  },
  {
    word: 'Иуда Искариот',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Предал Учителя за тридцать сребреников.',
    ref: [B.mat, 26, 15],
  },
  {
    word: 'Фома',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Ученик, не поверивший, пока не увидел раны своими глазами.',
    ref: [B.jhn, 20, 25],
  },
  {
    word: 'Матфей',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Мытарь, вставший из-за стола пошлин и пошедший за Иисусом.',
    ref: [B.mat, 9, 9],
  },
  {
    word: 'Иоанн Богослов',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Ученик, которого Иисус любил, возлежавший у Него на груди.',
    ref: [B.jhn, 13, 23],
  },
  {
    word: 'Сыны громовы',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Прозвище, данное Иисусом двум братьям-рыбакам.',
    ref: [B.mrk, 3, 17],
  },
  {
    word: 'Павел',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Гнал церковь, ослеп по дороге в Дамаск и стал апостолом.',
    ref: [B.act, 9, 3],
  },
  {
    word: 'Лука',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Врач, написавший Евангелие и книгу Деяний.',
    ref: [B.col, 4, 14],
  },
  {
    word: 'Марфа',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Заботилась об угощении, пока сестра слушала Учителя.',
    ref: [B.luk, 10, 40],
  },
  {
    word: 'Лазарь',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Пролежал во гробе четыре дня и вышел на зов.',
    ref: [B.jhn, 11, 43],
  },
  {
    word: 'Мария Магдалина',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Первая, кто увидел воскресшего и узнал Его по голосу.',
    ref: [B.jhn, 20, 16],
  },
  {
    word: 'Закхей',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Мытарь малого роста, влезший на смоковницу.',
    ref: [B.luk, 19, 4],
  },
  {
    word: 'Пилат',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Умыл руки перед толпой, отдав приговор.',
    ref: [B.mat, 27, 24],
  },
  {
    word: 'Ирод',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Царь, приказавший истребить младенцев в Вифлееме.',
    ref: [B.mat, 2, 16],
  },
  {
    word: 'Варавва',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Разбойник, отпущенный толпой вместо Иисуса.',
    ref: [B.mat, 27, 21],
  },
  {
    word: 'Каиафа',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Первосвященник, сказавший, что лучше одному умереть за народ.',
    ref: [B.jhn, 11, 50],
  },
  {
    word: 'Благоразумный разбойник',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Распятый рядом, услышавший «ныне же будешь со Мною в раю».',
    ref: [B.luk, 23, 43],
  },
  {
    word: 'Стефан',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Первый мученик церкви, побитый камнями.',
    ref: [B.act, 7, 59],
  },
  {
    word: 'Варнава',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Спутник Павла, чьё прозвище значит «сын утешения».',
    ref: [B.act, 4, 36],
  },
  {
    word: 'Никодим',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Фарисей, пришедший к Иисусу ночью с вопросом о новом рождении.',
    ref: [B.jhn, 3, 2],
  },
  {
    word: 'Корнилий',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Сотник, ставший первым язычником, принявшим крещение.',
    ref: [B.act, 10, 1],
  },
  {
    word: 'Тимофей',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Молодой сотрудник Павла, которому тот писал как сыну.',
    ref: [B.ti1, 1, 2],
  },
  {
    word: 'Гамалиил',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Учитель закона, посоветовавший совету оставить апостолов в покое.',
    ref: [B.act, 5, 38],
  },
  {
    word: 'Анания и Сапфира',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Супруги, солгавшие о цене проданного поля.',
    ref: [B.act, 5, 1],
  },
  {
    word: 'Лидия',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Торговка багряницей, первая уверовавшая в Европе.',
    ref: [B.act, 16, 14],
  },
  {
    word: 'Сила',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Спутник Павла, певший с ним в темнице около полуночи.',
    ref: [B.act, 16, 25],
  },
  {
    word: 'Онисим',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Беглый раб, которого Павел отослал назад — уже как брата.',
    ref: [B.phm, 1, 16],
  },
  {
    word: 'Захария',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Священник, онемевший до самого рождения сына.',
    ref: [B.luk, 1, 20],
  },
  {
    word: 'Елисавета',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Мать Иоанна Крестителя, родственница Марии.',
    ref: [B.luk, 1, 57],
  },
  {
    word: 'Симеон',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Старец, принявший Младенца на руки в храме.',
    ref: [B.luk, 2, 28],
  },
  {
    word: 'Мытарь',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Сборщик податей — в те времена почти синоним предателя.',
    ref: [B.luk, 18, 13],
  },
  {
    word: 'Фарисей',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Ревнитель закона, знавший правила лучше всех.',
    ref: [B.luk, 18, 11],
  },
  {
    word: 'Саддукей',
    difficulty: H,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Представитель течения, отвергавшего воскресение мёртвых.',
    ref: [B.mat, 22, 23],
  },
  {
    word: 'Волхвы',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Пришли с востока по звезде и принесли дары Младенцу.',
    ref: [B.mat, 2, 11],
  },
  {
    word: 'Сотник',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Римский офицер, сказавший «скажи только слово».',
    ref: [B.mat, 8, 8],
  },
  {
    word: 'Самарянин',
    difficulty: M,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Чужак, который остановился у избитого на дороге.',
    ref: [B.luk, 10, 33],
  },
  {
    word: 'Сатана',
    difficulty: E,
    category: 'PERSON',
    testament: 'BOTH',
    gloss: 'Противник: в начале — змей, в конце — дракон.',
    ref: [B.rev, 12, 9],
  },
  {
    word: 'Михаил',
    difficulty: H,
    category: 'PERSON',
    testament: 'BOTH',
    gloss: 'Архангел, воевавший с драконом во главе небесного воинства.',
    ref: [B.rev, 12, 7],
  },

  {
    word: 'Иисус Христос',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Плотник из Назарета, о Котором вся эта книга.',
  },
  {
    word: 'Змей',
    difficulty: E,
    category: 'PERSON',
    testament: 'OLD',
    gloss: 'Тот, кто первым спросил: «подлинно ли сказал Бог?»',
    ref: [B.gen, 3, 1],
  },
  {
    word: 'Пастухи',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss:
      'Первые, кому ангел сообщил о Рождестве, — они стерегли стадо ночью.',
    ref: [B.luk, 2, 8],
  },
  {
    word: 'Рыбаки',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Кем были первые ученики, пока не оставили сети на берегу.',
    ref: [B.mat, 4, 18],
  },
  {
    word: 'Двенадцать апостолов',
    difficulty: E,
    category: 'PERSON',
    testament: 'NEW',
    gloss: 'Столько учеников Иисус избрал и послал.',
    ref: [B.mat, 10, 1],
  },

  // ——— МЕСТА ———
  {
    word: 'Едем',
    difficulty: E,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Сад, где жили первые люди.',
    ref: [B.gen, 2, 8],
  },
  {
    word: 'Вавилон',
    difficulty: E,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Город башни и смешения языков, позже — символ гордыни.',
    ref: [B.gen, 11, 9],
  },
  {
    word: 'Ур Халдейский',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Город, из которого вышла семья Авраама.',
    ref: [B.gen, 11, 31],
  },
  {
    word: 'Вефиль',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Место, где Иакову приснилась лестница до неба.',
    ref: [B.gen, 28, 19],
  },
  {
    word: 'Мория',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Гора, куда Авраам повёл сына, и место будущего храма.',
    ref: [B.gen, 22, 2],
  },
  {
    word: 'Мамврийская дубрава',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Роща, где Авраам принял у входа в шатёр трёх путников.',
    ref: [B.gen, 18, 1],
  },
  {
    word: 'Синай',
    difficulty: M,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Гора, где Моисей получил заповеди.',
    ref: [B.exo, 19, 20],
  },
  {
    word: 'Красное море',
    difficulty: E,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Оно же Чермное: расступилось перед народом при исходе.',
    ref: [B.exo, 14, 21],
  },
  {
    word: 'Иерихон',
    difficulty: E,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Город, чьи стены пали после семи дней обхода.',
    ref: [B.jos, 6, 20],
  },
  {
    word: 'Кармил',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Гора, где Илия один вышел против пророков Ваала.',
    ref: [B.kg1, 18, 38],
  },
  {
    word: 'Иерусалим',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Город Давида, где стоял храм.',
  },
  {
    word: 'Сион',
    difficulty: M,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Гора в Иерусалиме и поэтическое имя самого города.',
  },
  {
    word: 'Вифлеем',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Город Давида и место рождения Иисуса.',
    ref: [B.mic, 5, 2],
  },
  {
    word: 'Назарет',
    difficulty: E,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Городок, где вырос Иисус.',
    ref: [B.mat, 2, 23],
  },
  {
    word: 'Галилея',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Область у моря, где Иисус призвал первых учеников.',
    ref: [B.mat, 4, 18],
  },
  {
    word: 'Капернаум',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Приморский город, который Иисус сделал Себе «своим».',
    ref: [B.mat, 9, 1],
  },
  {
    word: 'Геннисаретское озеро',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Оно же Галилейское море — там ловили рыбу первые ученики.',
    ref: [B.luk, 5, 1],
  },
  {
    word: 'Иордан',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Река, где крестил Иоанн и через которую народ вошёл в землю.',
    ref: [B.mat, 3, 13],
  },
  {
    word: 'Гефсимания',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Сад, где Иисус молился в ночь перед взятием под стражу.',
    ref: [B.mat, 26, 36],
  },
  {
    word: 'Голгофа',
    difficulty: E,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Место распятия; название значит «лобное место».',
    ref: [B.mat, 27, 33],
  },
  {
    word: 'Елеонская гора',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Гора напротив Иерусалима, откуда Иисус вознёсся.',
    ref: [B.act, 1, 12],
  },
  {
    word: 'Вифания',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Селение Марфы, Марии и Лазаря близ Иерусалима.',
    ref: [B.jhn, 11, 1],
  },
  {
    word: 'Кана',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Место первого чуда — воды, ставшей вином.',
    ref: [B.jhn, 2, 11],
  },
  {
    word: 'Египет',
    difficulty: E,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Страна рабства, из которой был выведен народ.',
  },
  {
    word: 'Ниневия',
    difficulty: H,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Огромный город, покаявшийся после проповеди Ионы.',
    ref: [B.jon, 3, 5],
  },
  {
    word: 'Содом',
    difficulty: M,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Город, уничтоженный за нечестие; жена Лота обернулась на него.',
    ref: [B.gen, 19, 24],
  },
  {
    word: 'Ханаан',
    difficulty: M,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Обещанная земля, текущая молоком и мёдом.',
    ref: [B.exo, 3, 8],
  },
  {
    word: 'Мёртвое море',
    difficulty: M,
    category: 'PLACE',
    testament: 'OLD',
    gloss: 'Солёное море на юге, где не живёт рыба.',
  },
  {
    word: 'Пустыня',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Место сорока лет странствия и сорока дней поста.',
  },
  {
    word: 'Храм',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Дом Божий в Иерусалиме, где однажды опрокинули столы менял.',
    ref: [B.mat, 21, 12],
  },
  {
    word: 'Синагога',
    difficulty: M,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Дом собрания, где по субботам читали свитки.',
    ref: [B.luk, 4, 16],
  },
  {
    word: 'Самария',
    difficulty: M,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Область, через которую иудеи старались не ходить.',
    ref: [B.jhn, 4, 4],
  },
  {
    word: 'Иудея',
    difficulty: M,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Южная область со столицей в Иерусалиме.',
  },
  {
    word: 'Тир и Сидон',
    difficulty: H,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Приморские города, которым, по слову Иисуса, будет отраднее.',
    ref: [B.mat, 11, 22],
  },
  {
    word: 'Дамаск',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Город, по дороге в который Савл увидел свет с неба.',
    ref: [B.act, 9, 3],
  },
  {
    word: 'Антиохия',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Город, где учеников впервые назвали христианами.',
    ref: [B.act, 11, 26],
  },
  {
    word: 'Ареопаг',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Холм и совет в Афинах, где Павел говорил о «неведомом Боге».',
    ref: [B.act, 17, 22],
  },
  {
    word: 'Афины',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Город философов, где Павел возмутился множеством идолов.',
    ref: [B.act, 17, 16],
  },
  {
    word: 'Ефес',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Город с храмом Артемиды, где Павел провёл около трёх лет.',
    ref: [B.act, 19, 10],
  },
  {
    word: 'Коринф',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Портовый город, чьей церкви Павел написал главу о любви.',
    ref: [B.co1, 13, 1],
  },
  {
    word: 'Македония',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Область, куда Павла позвали в ночном видении.',
    ref: [B.act, 16, 9],
  },
  {
    word: 'Рим',
    difficulty: M,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Столица империи, куда Павла привезли под стражей.',
    ref: [B.act, 28, 16],
  },
  {
    word: 'Патмос',
    difficulty: H,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Остров, где Иоанн получил Откровение.',
    ref: [B.rev, 1, 9],
  },

  {
    word: 'Небеса',
    difficulty: E,
    category: 'PLACE',
    testament: 'BOTH',
    gloss: 'Откуда приходят вестники и куда возносятся.',
  },
  {
    word: 'Вертеп',
    difficulty: E,
    category: 'PLACE',
    testament: 'NEW',
    gloss: 'Пещера для скота, где не нашлось места в гостинице.',
    ref: [B.luk, 2, 7],
  },

  // ——— СОБЫТИЯ ———
  {
    word: 'Творение',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Шесть дней, в которые Бог сотворил мир, и седьмой день покоя.',
    ref: [B.gen, 1, 1],
  },
  {
    word: 'Грехопадение',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Змей, плод и изгнание из сада.',
    ref: [B.gen, 3, 6],
  },
  {
    word: 'Потоп',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Сорок дней дождя, после которых землю покрыла вода.',
    ref: [B.gen, 7, 12],
  },
  {
    word: 'Вавилонская башня',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Стройка до небес, окончившаяся смешением языков.',
    ref: [B.gen, 11, 4],
  },
  {
    word: 'Жертвоприношение Исаака',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Нож занесён — и голос с неба остановил руку.',
    ref: [B.gen, 22, 12],
  },
  {
    word: 'Лестница Иакова',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Сон о лестнице, по которой восходили и нисходили ангелы.',
    ref: [B.gen, 28, 12],
  },
  {
    word: 'Сны фараона',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Семь тучных коров и семь тощих, которые их съели.',
    ref: [B.gen, 41, 4],
  },
  {
    word: 'Исход',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Выход народа из египетского рабства.',
    ref: [B.exo, 12, 41],
  },
  {
    word: 'Казни египетские',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Десять бедствий, после которых фараон отпустил народ.',
    ref: [B.exo, 7, 14],
  },
  {
    word: 'Переход через море',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Вода расступилась, и народ прошёл посуху.',
    ref: [B.exo, 14, 21],
  },
  {
    word: 'Дарование закона',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Гром, дым и голос на горе, к которой нельзя было подходить.',
    ref: [B.exo, 19, 18],
  },
  {
    word: 'Сорок лет в пустыне',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Странствие целого поколения на пути в обещанную землю.',
    ref: [B.num, 14, 33],
  },
  {
    word: 'Двенадцать соглядатаев',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Разведчики принесли гроздь винограда на шесте — и страх.',
    ref: [B.num, 13, 23],
  },
  {
    word: 'Помазание Давида',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Самуил выбрал младшего, которого даже не позвали с поля.',
    ref: [B.sa1, 16, 13],
  },
  {
    word: 'Давид и Голиаф',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Пять гладких камней из ручья против великана.',
    ref: [B.sa1, 17, 40],
  },
  {
    word: 'Суд Соломона',
    difficulty: M,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Спор двух женщин о ребёнке, решённый предложением рассечь его.',
    ref: [B.kg1, 3, 25],
  },
  {
    word: 'Разделение царства',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'После Соломона страна распалась на две.',
    ref: [B.kg1, 12, 19],
  },
  {
    word: 'Вавилонский плен',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Семьдесят лет, которые народ провёл на чужой земле.',
    ref: [B.jer, 29, 10],
  },
  {
    word: 'Возвращение из плена',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Указ царя, разрешивший вернуться и отстроить храм.',
    ref: [B.ezr, 1, 2],
  },
  {
    word: 'Огненная печь',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Трое друзей Даниила вышли из огня, не пропахнув дымом.',
    ref: [B.dan, 3, 27],
  },
  {
    word: 'Ров со львами',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Ночь Даниила среди львов, которым Бог заградил пасти.',
    ref: [B.dan, 6, 22],
  },
  {
    word: 'Неопалимая купина',
    difficulty: H,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Куст, который горел и не сгорал, когда Бог заговорил с Моисеем.',
    ref: [B.exo, 3, 2],
  },
  {
    word: 'Золотой телец',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'Идол, отлитый народом, пока Моисей был на горе.',
    ref: [B.exo, 32, 4],
  },
  {
    word: 'Пасха',
    difficulty: E,
    category: 'EVENT',
    testament: 'BOTH',
    gloss:
      'Праздник в память об исходе; в Новом Завете — время последней вечери.',
    ref: [B.exo, 12, 11],
  },
  {
    word: 'Благовещение',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Ангел пришёл к девушке из Назарета с вестью.',
    ref: [B.luk, 1, 31],
  },
  {
    word: 'Рождество',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Рождение Иисуса в Вифлееме, в яслях.',
    ref: [B.luk, 2, 7],
  },
  {
    word: 'Бегство в Египет',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Ночной уход семьи от царского гнева.',
    ref: [B.mat, 2, 14],
  },
  {
    word: 'Крещение',
    difficulty: E,
    category: 'EVENT',
    testament: 'BOTH',
    gloss: 'Погружение в воду как знак нового начала.',
    ref: [B.mat, 3, 16],
  },
  {
    word: 'Искушение в пустыне',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Сорок дней поста и три предложения от искусителя.',
    ref: [B.mat, 4, 1],
  },
  {
    word: 'Нагорная проповедь',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Слова, сказанные с горы множеству народа.',
    ref: [B.mat, 5, 1],
  },
  {
    word: 'Чудесный улов',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'После ночи без единой рыбы сети начали рваться.',
    ref: [B.luk, 5, 6],
  },
  {
    word: 'Усмирение бури',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Он спал на корме, а потом сказал морю: «умолкни».',
    ref: [B.mrk, 4, 39],
  },
  {
    word: 'Насыщение пяти тысяч',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Пять хлебов и две рыбы, которых хватило всем.',
    ref: [B.mat, 14, 19],
  },
  {
    word: 'Хождение по водам',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Иисус шёл по морю, а Пётр начал тонуть.',
    ref: [B.mat, 14, 29],
  },
  {
    word: 'Преображение',
    difficulty: H,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Иисус просиял на горе перед тремя учениками.',
    ref: [B.mat, 17, 2],
  },
  {
    word: 'Вход в Иерусалим',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Осёл, ветви по дороге и крик «осанна».',
    ref: [B.mat, 21, 8],
  },
  {
    word: 'Изгнание торговцев',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Опрокинутые столы менял и бич из верёвок.',
    ref: [B.jhn, 2, 15],
  },
  {
    word: 'Тайная вечеря',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Последний ужин Иисуса с учениками, где преломлён хлеб.',
    ref: [B.luk, 22, 19],
  },
  {
    word: 'Умовение ног',
    difficulty: H,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Учитель взял полотенце и опоясался им перед учениками.',
    ref: [B.jhn, 13, 5],
  },
  {
    word: 'Отречение Петра',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Трижды — и тут запел петух.',
    ref: [B.luk, 22, 61],
  },
  {
    word: 'Распятие',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Три креста, тьма по всей земле и разодранная завеса.',
    ref: [B.mat, 27, 45],
  },
  {
    word: 'Воскресение',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Пустой гроб на третий день.',
    ref: [B.mat, 28, 6],
  },
  {
    word: 'Вознесение',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Иисус поднялся на глазах учеников, и облако скрыло Его.',
    ref: [B.act, 1, 9],
  },
  {
    word: 'Пятидесятница',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Сошествие Духа, когда ученики заговорили на разных языках.',
    ref: [B.act, 2, 4],
  },
  {
    word: 'Обращение Савла',
    difficulty: M,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Свет с неба и голос: «что ты гонишь Меня?»',
    ref: [B.act, 9, 4],
  },
  {
    word: 'Кораблекрушение',
    difficulty: H,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Буря, выбросившая Павла с кораблём на остров.',
    ref: [B.act, 27, 41],
  },

  {
    word: 'Вифлеемская звезда',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'По ней волхвы нашли дорогу к Младенцу.',
    ref: [B.mat, 2, 9],
  },
  {
    word: 'Избиение младенцев',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Приказ царя, испугавшегося вести о новорождённом Царе.',
    ref: [B.mat, 2, 16],
  },
  {
    word: 'Изгнание из рая',
    difficulty: E,
    category: 'EVENT',
    testament: 'OLD',
    gloss: 'У входа поставили херувима с пламенным мечом.',
    ref: [B.gen, 3, 24],
  },
  {
    word: 'Воскрешение Лазаря',
    difficulty: E,
    category: 'EVENT',
    testament: 'NEW',
    gloss: 'Четыре дня во гробе — и голос снаружи: «иди вон».',
    ref: [B.jhn, 11, 43],
  },

  // ——— ПРЕДМЕТЫ ———
  {
    word: 'Ковчег',
    difficulty: E,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Судно, которое Ной строил по данным ему размерам.',
    ref: [B.gen, 6, 15],
  },
  {
    word: 'Радуга',
    difficulty: E,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Знак обещания, что потопа больше не будет.',
    ref: [B.gen, 9, 13],
  },
  {
    word: 'Масличная ветвь',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Лист, принесённый голубем: знак, что вода сошла.',
    ref: [B.gen, 8, 11],
  },
  {
    word: 'Чечевичная похлёбка',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Обед, за который отдали право старшего сына.',
    ref: [B.gen, 25, 34],
  },
  {
    word: 'Разноцветная одежда',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Подарок отца, из-за которого братья возненавидели Иосифа.',
    ref: [B.gen, 37, 3],
  },
  {
    word: 'Манна',
    difficulty: E,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Пища, которую народ собирал в пустыне каждое утро.',
    ref: [B.exo, 16, 31],
  },
  {
    word: 'Жезл',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Посох Моисея, обратившийся в змея перед фараоном.',
    ref: [B.exo, 7, 10],
  },
  {
    word: 'Огненный столп',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Вёл народ ночью; днём на его месте был облачный.',
    ref: [B.exo, 13, 21],
  },
  {
    word: 'Скрижали',
    difficulty: E,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Каменные доски с заповедями, написанными перстом Божиим.',
    ref: [B.exo, 31, 18],
  },
  {
    word: 'Ковчег завета',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Позолоченный ларец со скрижалями, который несли на шестах.',
    ref: [B.exo, 25, 10],
  },
  {
    word: 'Скиния',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Переносной шатёр для богослужения в пустыне.',
    ref: [B.exo, 26, 1],
  },
  {
    word: 'Семисвечник',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Золотой светильник на семь лампад в святилище.',
    ref: [B.exo, 25, 31],
  },
  {
    word: 'Ефод',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Наплечная одежда первосвященника с камнями по числу колен.',
    ref: [B.exo, 28, 6],
  },
  {
    word: 'Урим и туммим',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Предметы в наперснике первосвященника для вопрошания Бога.',
    ref: [B.exo, 28, 30],
  },
  {
    word: 'Хлебы предложения',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Двенадцать хлебов, постоянно лежавших перед Господом.',
    ref: [B.lev, 24, 5],
  },
  {
    word: 'Медный змей',
    difficulty: H,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Змей на шесте: взглянувший на него оставался жив.',
    ref: [B.num, 21, 9],
  },
  {
    word: 'Праща',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Оружие, которым пастух победил великана.',
    ref: [B.sa1, 17, 40],
  },
  {
    word: 'Гусли',
    difficulty: M,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Инструмент Давида, от звука которого отступала тоска царя.',
    ref: [B.sa1, 16, 23],
  },
  {
    word: 'Свиток',
    difficulty: M,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Книга тех времён — длинная лента, свёрнутая в рулон.',
  },
  {
    word: 'Труба',
    difficulty: M,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Рог, от звука которого падали стены и который возвестит конец.',
  },
  {
    word: 'Светильник',
    difficulty: M,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Масляная лампа; её ставят не под сосуд, а на подсвечник.',
    ref: [B.mat, 5, 15],
  },
  {
    word: 'Кадило',
    difficulty: H,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Сосуд для курения фимиама при богослужении.',
  },
  {
    word: 'Виссон',
    difficulty: H,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Тончайшая дорогая ткань, знак чистоты и достатка.',
  },
  {
    word: 'Точило',
    difficulty: H,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Давильня, где ногами выжимали виноградный сок.',
  },
  {
    word: 'Кимвал',
    difficulty: H,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Медная тарелка; без любви человек — всего лишь она.',
    ref: [B.co1, 13, 1],
  },
  {
    word: 'Ясли',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Кормушка для скота, ставшая колыбелью.',
    ref: [B.luk, 2, 7],
  },
  {
    word: 'Сети',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Снасть рыбаков, которую первые ученики оставили на берегу.',
    ref: [B.mat, 4, 20],
  },
  {
    word: 'Рыба',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Её ловили ученики, и двух хватило на пять тысяч человек.',
    ref: [B.mat, 14, 17],
  },
  {
    word: 'Петух',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Его крик напомнил ученику слова Учителя.',
    ref: [B.mat, 26, 74],
  },
  {
    word: 'Осёл',
    difficulty: E,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'На нём въехали в Иерусалим, и однажды он заговорил.',
  },
  {
    word: 'Овца',
    difficulty: E,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Животное, с которым чаще всего сравнивают людей.',
  },
  {
    word: 'Виноградная лоза',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Растение, которым Иисус назвал Себя, а учеников — ветвями.',
    ref: [B.jhn, 15, 5],
  },
  {
    word: 'Новые мехи',
    difficulty: H,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Только в них вливают молодое вино.',
    ref: [B.mat, 9, 17],
  },
  {
    word: 'Динарий',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Монета с изображением кесаря и дневная плата работнику.',
    ref: [B.mat, 22, 19],
  },
  {
    word: 'Лепта',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Самая мелкая монета; двух таких хватило, чтобы превзойти всех.',
    ref: [B.mrk, 12, 42],
  },
  {
    word: 'Алавастровый сосуд',
    difficulty: H,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Сосуд с драгоценным миром, разбитый ради Него.',
    ref: [B.mrk, 14, 3],
  },
  {
    word: 'Терновый венец',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Венец из колючих ветвей, надетый воинами в насмешку.',
    ref: [B.mat, 27, 29],
  },
  {
    word: 'Тридцать сребреников',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Цена предательства, брошенная потом в храме.',
    ref: [B.mat, 27, 5],
  },
  {
    word: 'Крест',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Орудие римской казни, ставшее знаком спасения.',
  },
  {
    word: 'Копьё',
    difficulty: H,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Им пронзили рёбра, и тотчас истекли кровь и вода.',
    ref: [B.jhn, 19, 34],
  },
  {
    word: 'Камень от гроба',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Его нашли отваленным, а был он весьма велик.',
    ref: [B.mrk, 16, 4],
  },
  {
    word: 'Пелены',
    difficulty: H,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'То, что осталось лежать в пустом гробу.',
    ref: [B.jhn, 20, 7],
  },
  {
    word: 'Хлеб и вино',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'То, что Иисус подал ученикам на последней вечере.',
    ref: [B.luk, 22, 19],
  },

  {
    word: 'Голубь',
    difficulty: E,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Принёс ветку после потопа и сошёл при крещении.',
  },
  {
    word: 'Кит',
    difficulty: E,
    category: 'OBJECT',
    testament: 'OLD',
    gloss: 'Большая рыба, проглотившая беглого пророка на три дня.',
    ref: [B.jon, 1, 17],
  },
  {
    word: 'Лев',
    difficulty: E,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'Ему заградили пасть во рву, и им же назвали колено Иуды.',
  },
  {
    word: 'Хлеб',
    difficulty: E,
    category: 'OBJECT',
    testament: 'BOTH',
    gloss: 'О нём просят в молитве, и пятью такими насытили толпу.',
  },
  {
    word: 'Лодка',
    difficulty: E,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'С неё Иисус учил народ и в ней же спал во время бури.',
  },
  {
    word: 'Верблюд',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Ему легче пройти сквозь игольные уши, чем богатому — в Царство.',
    ref: [B.mat, 19, 24],
  },
  {
    word: 'Меч',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Им отсекли ухо, и услышали: «вложи его в ножны».',
    ref: [B.jhn, 18, 11],
  },
  {
    word: 'Колодец',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'У него Иисус попросил пить у самарянки.',
    ref: [B.jhn, 4, 6],
  },
  {
    word: 'Пальмовые ветви',
    difficulty: M,
    category: 'OBJECT',
    testament: 'NEW',
    gloss: 'Их взяли навстречу Входящему в город.',
    ref: [B.jhn, 12, 13],
  },

  // ——— ПОНЯТИЯ ———
  {
    word: 'Завет',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Договор между Богом и людьми, с обещанием и условием.',
  },
  {
    word: 'Пророк',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Тот, кто говорит от имени Бога — часто вопреки всем.',
  },
  {
    word: 'Апостол',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Посланник; так названы ближайшие ученики Иисуса.',
  },
  {
    word: 'Ангел',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Вестник, которого посылают с неба.',
  },
  {
    word: 'Рай',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, что было обещано разбойнику на кресте «ныне же».',
    ref: [B.luk, 23, 43],
  },
  {
    word: 'Ад',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Место, о котором Иисус говорил как о геенне огненной.',
    ref: [B.mat, 5, 22],
  },
  {
    word: 'Грех',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Промах мимо цели; то, что отделяет человека от Бога.',
  },
  {
    word: 'Покаяние',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Перемена ума и разворот от прежнего пути.',
  },
  {
    word: 'Прощение',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Не семь раз, а до семижды семидесяти.',
    ref: [B.mat, 18, 22],
  },
  {
    word: 'Милость',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Не дать заслуженного наказания.',
  },
  {
    word: 'Благодать',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Дар, который нельзя заработать.',
  },
  {
    word: 'Вера',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Осуществление ожидаемого и уверенность в невидимом.',
    ref: [B.heb, 11, 1],
  },
  {
    word: 'Надежда',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Вторая из трёх, что пребывают вместе с верой и любовью.',
    ref: [B.co1, 13, 13],
  },
  {
    word: 'Любовь',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Долготерпит, милосердствует и никогда не перестаёт.',
    ref: [B.co1, 13, 4],
  },
  {
    word: 'Чудо',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, чего не объяснить обычным ходом вещей.',
  },
  {
    word: 'Притча',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Короткая история, за которой стоит совсем другое.',
  },
  {
    word: 'Евангелие',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Слово, означающее «добрая весть»; таких книг четыре.',
  },
  {
    word: 'Мессия',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Помазанник, которого ждали; по-гречески — Христос.',
  },
  {
    word: 'Молитва',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Разговор с Богом; образцу её Иисус научил учеников.',
    ref: [B.mat, 6, 9],
  },
  {
    word: 'Пост',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Добровольный отказ от пищи ради молитвы.',
  },
  {
    word: 'Милостыня',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Делают так, чтобы левая рука не знала, что делает правая.',
    ref: [B.mat, 6, 3],
  },
  {
    word: 'Жертва',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, что отдают Богу, отказываясь от этого себе.',
  },
  {
    word: 'Идол',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, чему поклоняются вместо Бога.',
  },
  {
    word: 'Десятина',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Десятая часть, отделяемая Богу.',
    ref: [B.mal, 3, 10],
  },
  {
    word: 'Суббота',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'День покоя, заповеданный в память о творении.',
    ref: [B.exo, 20, 8],
  },
  {
    word: 'Заповедь',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Данное Богом повеление; на скрижалях их было десять.',
  },
  {
    word: 'Первородство',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Право старшего сына, отданное однажды за похлёбку.',
    ref: [B.gen, 25, 33],
  },
  {
    word: 'Обрезание',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Знак завета Авраама на теле.',
    ref: [B.gen, 17, 11],
  },
  {
    word: 'Кущи',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Праздник шалашей в память о пути по пустыне.',
    ref: [B.lev, 23, 42],
  },
  {
    word: 'Юбилейный год',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Каждый пятидесятый: долги прощались, земля возвращалась.',
    ref: [B.lev, 25, 10],
  },
  {
    word: 'Города-убежища',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Города, где мог укрыться убивший ненамеренно.',
    ref: [B.num, 35, 11],
  },
  {
    word: 'Левират',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Обычай, по которому брат брал вдову умершего брата.',
    ref: [B.deu, 25, 5],
  },
  {
    word: 'Двенадцать колен',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Роды Израиля по числу сыновей Иакова.',
  },
  {
    word: 'Мудрость',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Её начало — страх Господень.',
    ref: [B.pro, 9, 10],
  },
  {
    word: 'Гордыня',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Она идёт впереди падения.',
    ref: [B.pro, 16, 18],
  },
  {
    word: 'Смирение',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Кто унижает себя, тот возвысится.',
    ref: [B.luk, 14, 11],
  },
  {
    word: 'Терпение',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, без чего не приносят плода.',
    ref: [B.luk, 8, 15],
  },
  {
    word: 'Служение',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Кто хочет быть первым, да будет всем слугой.',
    ref: [B.mrk, 10, 44],
  },
  {
    word: 'Спасение',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'То, ради чего Сын Человеческий пришёл взыскать погибшее.',
    ref: [B.luk, 19, 10],
  },
  {
    word: 'Оправдание',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Признание праведным не по делам, а по вере.',
    ref: [B.rom, 3, 28],
  },
  {
    word: 'Искупление',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Выкуп, которым возвращают своё.',
  },
  {
    word: 'Свобода',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'К ней ведёт истина, которую надо познать.',
    ref: [B.jhn, 8, 32],
  },
  {
    word: 'Троица',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Отец, Сын и Святой Дух — одно имя при крещении.',
    ref: [B.mat, 28, 19],
  },
  {
    word: 'Царство Небесное',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'То, с чем Иисус сравнивал зерно, закваску и жемчужину.',
    ref: [B.mat, 13, 31],
  },
  {
    word: 'Воскресение мёртвых',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Надежда, из-за которой спорили фарисеи и саддукеи.',
    ref: [B.act, 23, 8],
  },
  {
    word: 'Плоды Духа',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Список, начинающийся с любви, радости и мира.',
    ref: [B.gal, 5, 22],
  },
  {
    word: 'Блаженства',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Начало Нагорной проповеди: «блаженны нищие духом…».',
    ref: [B.mat, 5, 3],
  },
  {
    word: 'Синедрион',
    difficulty: H,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Высший совет старейшин, судивший Иисуса.',
    ref: [B.mat, 26, 59],
  },
  {
    word: 'Апокалипсис',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Другое имя Откровения; значит «снятие покрова».',
  },
  {
    word: 'Соль земли',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Кем Иисус назвал Своих учеников в Нагорной проповеди.',
    ref: [B.mat, 5, 13],
  },
  {
    word: 'Пастырь',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Пастух; так Иисус назвал Себя, полагающего душу за овец.',
    ref: [B.jhn, 10, 11],
  },

  {
    word: 'Десять заповедей',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'OLD',
    gloss: 'Столько правил высечено на двух каменных досках.',
    ref: [B.exo, 20, 1],
  },
  {
    word: 'Душа',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Что толку приобрести весь мир, если её потерять.',
    ref: [B.mat, 16, 26],
  },
  {
    word: 'Церковь',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Собрание верующих, которое врата ада не одолеют.',
    ref: [B.mat, 16, 18],
  },
  {
    word: 'Ученик',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Тот, кто оставил своё и пошёл следом.',
  },
  {
    word: 'Проповедь',
    difficulty: E,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Речь, обращённая к тем, кто пришёл слушать.',
  },
  {
    word: 'Дух Святой',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Сошёл на учеников языками огня.',
    ref: [B.act, 2, 3],
  },
  {
    word: 'Вечная жизнь',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'То, ради чего «так возлюбил Бог мир».',
    ref: [B.jhn, 3, 16],
  },
  {
    word: 'Второе пришествие',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'Его ждут, но о дне и часе не знает никто.',
    ref: [B.mat, 24, 36],
  },
  {
    word: 'Страшный суд',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'NEW',
    gloss: 'День, когда откроются книги.',
    ref: [B.rev, 20, 12],
  },
  {
    word: 'Святой',
    difficulty: M,
    category: 'CONCEPT',
    testament: 'BOTH',
    gloss: 'Отделённый для Бога.',
  },

  // ——— ПРИТЧИ ———
  {
    word: 'Блудный сын',
    difficulty: E,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Ушёл, растратил всё и вернулся — а отец выбежал навстречу.',
    ref: [B.luk, 15, 20],
  },
  {
    word: 'Добрый самарянин',
    difficulty: E,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Чужак остановился там, где прошли мимо свои.',
    ref: [B.luk, 10, 33],
  },
  {
    word: 'Сеятель',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Одно семя — четыре почвы: дорога, камень, тернии, добрая земля.',
    ref: [B.mat, 13, 3],
  },
  {
    word: 'Талант',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Мера серебра; тот, кто закопал свою, остался ни с чем.',
    ref: [B.mat, 25, 25],
  },
  {
    word: 'Заблудшая овца',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Ради одной пастух оставляет девяносто девять.',
    ref: [B.luk, 15, 4],
  },
  {
    word: 'Потерянная драхма',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Зажгла свечу, вымела дом и искала, пока не нашла.',
    ref: [B.luk, 15, 8],
  },
  {
    word: 'Десять дев',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Пять запаслись маслом, пять — нет, и дверь затворилась.',
    ref: [B.mat, 25, 10],
  },
  {
    word: 'Горчичное зерно',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Самое малое из семян, вырастающее в дерево.',
    ref: [B.mat, 13, 31],
  },
  {
    word: 'Закваска',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Малое, от чего вскисает всё тесто.',
    ref: [B.mat, 13, 33],
  },
  {
    word: 'Драгоценная жемчужина',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Купец продал всё, что имел, чтобы купить одну.',
    ref: [B.mat, 13, 46],
  },
  {
    word: 'Сокровище в поле',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Нашёл, утаил и от радости продал всё, чтобы купить поле.',
    ref: [B.mat, 13, 44],
  },
  {
    word: 'Пшеница и плевелы',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Растут вместе до жатвы, а потом их разделят.',
    ref: [B.mat, 13, 30],
  },
  {
    word: 'Невод',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Сеть захватила всякую рыбу, а хорошую отобрали в сосуды.',
    ref: [B.mat, 13, 48],
  },
  {
    word: 'Немилосердный должник',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Ему простили огромный долг, а он не простил малого.',
    ref: [B.mat, 18, 28],
  },
  {
    word: 'Виноградари',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Нанятые в разное время получили одинаковую плату.',
    ref: [B.mat, 20, 9],
  },
  {
    word: 'Два сына',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Один сказал «не пойду» и пошёл, другой — наоборот.',
    ref: [B.mat, 21, 29],
  },
  {
    word: 'Брачный пир',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Званые не пришли, и позвали всех, кого нашли на дорогах.',
    ref: [B.mat, 22, 9],
  },
  {
    word: 'Овцы и козлы',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Разделение по одному вопросу: накормил ли ты голодного.',
    ref: [B.mat, 25, 33],
  },
  {
    word: 'Дом на песке',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Пошёл дождь, подул ветер — и падение его было великое.',
    ref: [B.mat, 7, 27],
  },
  {
    word: 'Мытарь и фарисей',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Двое молились в храме, а оправданным ушёл только один.',
    ref: [B.luk, 18, 14],
  },
  {
    word: 'Безумный богач',
    difficulty: M,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Собрался строить житницы побольше — и в ту же ночь.',
    ref: [B.luk, 12, 20],
  },
  {
    word: 'Богач и Лазарь',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Пировавший каждый день и нищий у ворот — и что было потом.',
    ref: [B.luk, 16, 20],
  },
  {
    word: 'Неверный управитель',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Уменьшил чужие долги, чтобы его приняли в дома.',
    ref: [B.luk, 16, 6],
  },
  {
    word: 'Неотступная вдова',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Судья уступил ей только потому, что она не отставала.',
    ref: [B.luk, 18, 5],
  },
  {
    word: 'Друг в полночь',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Дал не по дружбе, а по неотступности просящего.',
    ref: [B.luk, 11, 8],
  },
  {
    word: 'Строитель башни',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Сначала сядь и вычисли, хватит ли тебе на завершение.',
    ref: [B.luk, 14, 28],
  },
  {
    word: 'Два должника',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Кому больше простили, тот больше и любит.',
    ref: [B.luk, 7, 42],
  },
  {
    word: 'Смоковница',
    difficulty: H,
    category: 'PARABLE',
    testament: 'NEW',
    gloss: 'Дереву дали ещё один год, чтобы принесло плод.',
    ref: [B.luk, 13, 8],
  },

  // ——— КРЫЛАТЫЕ СЛОВА ———
  // Категория для тех, кто Библию не открывал: эти слова человек говорит
  // сам, каждый день, не зная, откуда они. Пояснение здесь работает как
  // маленькое открытие, а не как справка.
  {
    word: 'Манна небесная',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Так говорят о том, что достаётся даром и очень вовремя.',
    ref: [B.exo, 16, 15],
  },
  {
    word: 'Козёл отпущения',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'На него возлагали чужие грехи и отпускали в пустыню.',
    ref: [B.lev, 16, 10],
  },
  {
    word: 'Вавилонское столпотворение',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Полная неразбериха, где никто никого не понимает.',
    ref: [B.gen, 11, 7],
  },
  {
    word: 'Иерихонская труба',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Так говорят об очень громком голосе.',
    ref: [B.jos, 6, 20],
  },
  {
    word: 'Запретный плод',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'То, что нельзя, и оттого тянет сильнее всего.',
    ref: [B.gen, 3, 6],
  },
  {
    word: 'Земля обетованная',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Место, куда стремятся и где, кажется, всё будет хорошо.',
    ref: [B.heb, 11, 9],
  },
  {
    word: 'Око за око',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Правило равного воздаяния.',
    ref: [B.exo, 21, 24],
  },
  {
    word: 'Содом и Гоморра',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Полный хаос и разгул в одном отдельно взятом месте.',
    ref: [B.gen, 19, 24],
  },
  {
    word: 'Египетская тьма',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Такая темнота, что, как говорится, хоть глаз выколи.',
    ref: [B.exo, 10, 22],
  },
  {
    word: 'Каинова печать',
    difficulty: H,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Знак, по которому все узнают о преступлении.',
    ref: [B.gen, 4, 15],
  },
  {
    word: 'Соломоново решение',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Неожиданно мудрый выход из спора, где обе стороны стоят на своём.',
    ref: [B.kg1, 3, 25],
  },
  {
    word: 'Валтасаров пир',
    difficulty: H,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Веселье накануне гибели.',
    ref: [B.dan, 5, 5],
  },
  {
    word: 'Мене, текел, фарес',
    difficulty: H,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Надпись на стене: «взвешен и найден очень лёгким».',
    ref: [B.dan, 5, 25],
  },
  {
    word: 'Посыпать голову пеплом',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Открыто и напоказ горевать.',
    ref: [B.job, 2, 12],
  },
  {
    word: 'Иов многострадальный',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Так говорят о том, на кого беды сыплются одна за другой.',
  },
  {
    word: 'Допотопный',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Очень старый — буквально «ещё до того самого дождя».',
  },
  {
    word: 'От Адама',
    difficulty: M,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Начать рассказ с самого-самого начала.',
  },
  {
    word: 'Камень преткновения',
    difficulty: M,
    category: 'IDIOM',
    testament: 'BOTH',
    gloss: 'То, обо что все спотыкаются.',
    ref: [B.isa, 8, 14],
  },
  // Псалом 118, а не 117: в загруженном тексте Псалтирь пронумерована по
  // еврейской традиции, а синодальный номер стоит в скобках внутри стиха.
  // Ссылка должна открывать ту главу, которая реально есть в читалке.
  {
    word: 'Краеугольный камень',
    difficulty: M,
    category: 'IDIOM',
    testament: 'BOTH',
    gloss: 'Главное, на чём всё держится.',
    ref: [B.psa, 118, 22],
  },
  {
    word: 'Глас вопиющего в пустыне',
    difficulty: M,
    category: 'IDIOM',
    testament: 'BOTH',
    gloss: 'Призыв, которого никто не слышит.',
    ref: [B.isa, 40, 3],
  },
  {
    word: 'Не хлебом единым',
    difficulty: M,
    category: 'IDIOM',
    testament: 'BOTH',
    gloss: 'Человеку нужна не только сытость.',
    ref: [B.mat, 4, 4],
  },
  {
    word: 'Фома неверующий',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Тот, кто не поверит, пока сам не потрогает.',
    ref: [B.jhn, 20, 25],
  },
  {
    word: 'Умыть руки',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Снять с себя ответственность за происходящее.',
    ref: [B.mat, 27, 24],
  },
  {
    word: 'Поцелуй Иуды',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Предательство под видом дружбы.',
    ref: [B.luk, 22, 48],
  },
  {
    word: 'Внести свою лепту',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Сделать свой небольшой, но настоящий вклад.',
    ref: [B.mrk, 12, 42],
  },
  {
    word: 'Нести свой крест',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Терпеливо переносить то, что выпало именно тебе.',
    ref: [B.luk, 14, 27],
  },
  {
    word: 'Бросить камень',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Осудить первым, самому будучи не безгрешным.',
    ref: [B.jhn, 8, 7],
  },
  {
    word: 'Волк в овечьей шкуре',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Опасный человек с самым безобидным видом.',
    ref: [B.mat, 7, 15],
  },
  {
    word: 'Хлеб насущный',
    difficulty: E,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'То, без чего не прожить сегодняшний день.',
    ref: [B.mat, 6, 11],
  },
  {
    word: 'Метать бисер перед свиньями',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Говорить ценное тем, кто этого не оценит.',
    ref: [B.mat, 7, 6],
  },
  {
    word: 'Кесарю кесарево',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Каждому своё, по принадлежности.',
    ref: [B.mat, 22, 21],
  },
  {
    word: 'Не судите, да не судимы будете',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Самая цитируемая фраза в любом споре.',
    ref: [B.mat, 7, 1],
  },
  {
    word: 'Ищите и обрящете',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Ищите — и найдёте; так это звучит по-старому.',
    ref: [B.mat, 7, 7],
  },
  {
    word: 'Кто не работает, тот не ест',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Правило общины, которое потом стало лозунгом совсем других людей.',
    ref: [B.th2, 3, 10],
  },
  {
    word: 'Служить маммоне',
    difficulty: H,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Жить ради денег: двум господам не служат.',
    ref: [B.mat, 6, 24],
  },
  {
    word: 'Живая вода',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'То, что утоляет жажду раз и навсегда.',
    ref: [B.jhn, 4, 10],
  },
  {
    word: 'Альфа и омега',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Начало и конец; самое главное в деле.',
    ref: [B.rev, 1, 8],
  },
  {
    word: 'Тайна за семью печатями',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'То, чего не знает совершенно никто.',
    ref: [B.rev, 5, 1],
  },
  {
    word: 'Врачу, исцелися сам',
    difficulty: H,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Сначала разберись с собой, а потом поучай других.',
    ref: [B.luk, 4, 23],
  },
  {
    word: 'Ноев ковчег',
    difficulty: E,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Место, куда набилось слишком много всех подряд.',
    ref: [B.gen, 7, 7],
  },
  {
    word: 'Мафусаилов век',
    difficulty: H,
    category: 'IDIOM',
    testament: 'OLD',
    gloss: 'Так говорят об очень долгой жизни.',
    ref: [B.gen, 5, 27],
  },
  {
    word: 'Тьма кромешная',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Полная беспросветность; в Писании — «тьма внешняя».',
    ref: [B.mat, 8, 12],
  },
  {
    word: 'Питаться акридами',
    difficulty: H,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Жить впроголодь на чём придётся.',
    ref: [B.mat, 3, 4],
  },
  {
    word: 'Зарыть талант в землю',
    difficulty: M,
    category: 'IDIOM',
    testament: 'NEW',
    gloss: 'Не пустить в дело то, что тебе дано.',
    ref: [B.mat, 25, 18],
  },
];

/**
 * Проверяет банк до единой записи в базу. Всё, что здесь ловится, — это
 * ошибки, которые в игре выглядели бы как враньё: две карточки с одним
 * словом, пояснение в три строки или ссылка на стих, которого нет.
 */
async function validate(): Promise<void> {
  const problems: string[] = [];

  const seen = new Map<string, number>();
  for (const entry of WORDS) {
    seen.set(entry.word, (seen.get(entry.word) ?? 0) + 1);
    if (entry.gloss.length > 90) {
      problems.push(
        `«${entry.word}»: пояснение длиннее 90 символов (${entry.gloss.length})`,
      );
    }
    if (
      !entry.gloss.endsWith('.') &&
      !entry.gloss.endsWith('…') &&
      !entry.gloss.endsWith('»') &&
      !entry.gloss.endsWith('?')
    ) {
      problems.push(`«${entry.word}»: пояснение без завершающего знака`);
    }
  }
  for (const [word, count] of seen) {
    if (count > 1) problems.push(`«${word}»: встречается ${count} раза`);
  }

  // Ссылки сверяем с реальным текстом: книга, глава и стих должны
  // существовать. Это единственная проверка, которую нельзя сделать
  // «на глаз», и единственная, ошибка в которой видна пользователю.
  const refs = WORDS.filter((entry) => entry.ref);
  const found = await prisma.bibleVerse.findMany({
    where: {
      OR: refs.map((entry) => ({
        bookId: entry.ref![0],
        chapter: entry.ref![1],
        verse: entry.ref![2],
      })),
    },
    select: { bookId: true, chapter: true, verse: true },
  });
  const existing = new Set(
    found.map((v) => `${v.bookId}:${v.chapter}:${v.verse}`),
  );
  for (const entry of refs) {
    const [bookId, chapter, verse] = entry.ref!;
    if (!existing.has(`${bookId}:${chapter}:${verse}`)) {
      problems.push(
        `«${entry.word}»: стиха ${bookId} ${chapter}:${verse} нет в тексте`,
      );
    }
  }

  if (problems.length > 0) {
    console.error(`Банк не прошёл проверку (${problems.length}):`);
    for (const problem of problems) console.error(`  — ${problem}`);
    throw new Error('Банк слов содержит ошибки, ничего не записано');
  }
}

async function main(): Promise<void> {
  console.log(`Слов в наборе: ${WORDS.length}`);

  const verseCount = await prisma.bibleVerse.count();
  if (verseCount === 0) {
    throw new Error(
      'В базе нет текста Библии — сначала `pnpm --filter @bible-arena/api prisma:seed-bible`, ' +
        'иначе ссылки нечем проверить.',
    );
  }
  await validate();

  // upsert, а не пересоздание: сид запускают повторно, а партии ссылаются на
  // слова по id — пересоздание порвало бы эти ссылки без всякой пользы.
  let created = 0;
  let updated = 0;
  for (const entry of WORDS) {
    const fields = {
      difficulty: entry.difficulty,
      category: entry.category,
      testament: entry.testament,
      gloss: entry.gloss,
      refBookId: entry.ref?.[0] ?? null,
      refChapter: entry.ref?.[1] ?? null,
      refVerse: entry.ref?.[2] ?? null,
    };
    const existing = await prisma.aliasWord.findUnique({
      where: { word: entry.word },
      select: { id: true },
    });
    await prisma.aliasWord.upsert({
      where: { word: entry.word },
      create: { word: entry.word, ...fields },
      update: fields,
    });
    if (existing) {
      updated += 1;
    } else {
      created += 1;
    }
  }

  const byDifficulty = await prisma.aliasWord.groupBy({
    by: ['difficulty'],
    _count: { _all: true },
  });
  const byCategory = await prisma.aliasWord.groupBy({
    by: ['category'],
    _count: { _all: true },
  });
  const withoutReference = await prisma.aliasWord.count({
    where: { refBookId: null },
  });

  console.log(`Добавлено: ${created}, обновлено: ${updated}`);
  console.log('По уровню:');
  for (const row of byDifficulty) {
    console.log(`  ${row.difficulty}: ${row._count._all}`);
  }
  console.log('По категории:');
  for (const row of byCategory) {
    console.log(`  ${row.category}: ${row._count._all}`);
  }
  console.log(`Без ссылки на стих (сквозные понятия): ${withoutReference}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => void prisma.$disconnect());
